// seo-bot · edge/middleware-codegen — GENERATE Next.js 16 edge source for a client repo.
//
// Pure string-emitting functions (no I/O, no deploy) that produce:
//   1. generateProxy()          → a Next.js 16 `proxy.ts` that buckets the UA into an
//                                 x-bot-class header (ai-nojs|ai-search|social|googlebot|human).
//   2. generateMetadataSnippet()→ a `generateMetadata` override that reads the Edge Config
//                                 overlay written by apply/edge.mjs and applies head-only fixes.
//   3. graduate(rule)           → turn ONE live edge rule into a source-PR payload
//                                 (apply/nextjs.mjs patch/fileWrite shape) so edge hotfixes
//                                 graduate into permanent, server-rendered repo source.
//
// NEXT.JS 16 NOTES (verified against node_modules/next/dist/docs/, AGENTS.md mandate):
//   • Middleware was RENAMED to "Proxy" in Next 16 — the file is `proxy.ts` (project root or
//     /src), the exported function is `proxy` (named or default). `middleware.ts` is deprecated.
//   • Proxy DEFAULTS to the Node.js runtime; the `runtime` config option is NOT available in
//     proxy files and THROWS if set — so we never emit one.
//   • Request headers set for downstream consumers must use
//     `NextResponse.next({ request: { headers } })`, NOT `next({ headers })` (which leaks to client).
//   • The proxy must NOT vary on raw UA in a way that fragments the cache — it stamps a small,
//     low-cardinality class header read by generateMetadata; the page rendering is identical
//     per path (no per-user/per-agent BODY variance → no cloaking).
//   • generateMetadata is Server-Component-only and resolves on the server → the overlay fix
//     lands in the INITIAL HTML (visible to non-JS AI crawlers). That's the whole point.
//
// SAFETY: the generated metadata snippet only ever sets head fields (title/description/
// canonical/robots/og/twitter/alternates/JSON-LD). It never writes body text. The overlay it
// reads was already passed through edge/cloaking-guard at write time.

import { fieldOf } from './cloaking-guard.mjs';

/** AI / bot UA buckets. Kept in sync conceptually with connect/aibot-ips.mjs UA list. */
const UA_CLASSES = {
  // No-JS AI crawlers that read RAW HTML (the AEO-critical ones — must get full SSR).
  'ai-nojs': ['GPTBot', 'ClaudeBot', 'CCBot', 'Google-Extended', 'Bytespider', 'Amazonbot', 'Applebot-Extended', 'PerplexityBot'],
  // AI "search/answer" fetchers that act on a live user query.
  'ai-search': ['OAI-SearchBot', 'ChatGPT-User', 'Claude-User', 'Perplexity-User'],
  // Social unfurlers (OG/Twitter card scrapers).
  social: ['facebookexternalhit', 'Twitterbot', 'LinkedInBot', 'Slackbot', 'WhatsApp', 'Discordbot', 'TelegramBot', 'Pinterest'],
  // Classic search.
  googlebot: ['Googlebot', 'Bingbot', 'DuckDuckBot', 'YandexBot'],
};

/**
 * Generate a Next.js 16 `proxy.ts` that buckets UA → x-bot-class and forwards geo headers.
 * @param {{matcher?:string|string[]}} [opts]
 * @returns {string} proxy.ts source
 */
export function generateProxy({ matcher } = {}) {
  const matcherSrc = JSON.stringify(
    matcher || ['/((?!api|_next/static|_next/image|favicon.ico|sitemap.xml|robots.txt).*)'],
  );
  const classTable = JSON.stringify(UA_CLASSES, null, 2);
  return `// proxy.ts — GENERATED by seo-bot (edge/middleware-codegen). Next.js 16 Proxy.
// Buckets the request UA into a low-cardinality x-bot-class header so generateMetadata can
// guarantee server-rendered SEO for AI crawlers WITHOUT varying body content (no cloaking).
// NOTE (Next 16): the file is "proxy.ts" and the function is "proxy" (was middleware). Proxy
// runs on the Node.js runtime by default; do NOT add a \`runtime\` export — it throws here.
import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';

const UA_CLASSES: Record<string, string[]> = ${classTable};

/** First matching class, else "human". Order: ai-nojs > ai-search > social > googlebot. */
function classifyUA(ua: string): string {
  const s = ua || '';
  for (const cls of ['ai-nojs', 'ai-search', 'social', 'googlebot']) {
    if (UA_CLASSES[cls].some((sig) => s.includes(sig))) return cls;
  }
  return 'human';
}

export function proxy(request: NextRequest) {
  const ua = request.headers.get('user-agent') || '';
  const botClass = classifyUA(ua);

  // Forward the class + geo to the app via REQUEST headers (read by generateMetadata).
  // Use next({ request: { headers } }) so these are upstream-only (never leaked to client).
  const requestHeaders = new Headers(request.headers);
  requestHeaders.set('x-bot-class', botClass);
  const geo = (request as any).geo;
  if (geo?.country) requestHeaders.set('x-geo-country', geo.country);
  if (geo?.city) requestHeaders.set('x-geo-city', geo.city);

  return NextResponse.next({ request: { headers: requestHeaders } });
}

export const config = {
  matcher: ${matcherSrc},
};
`;
}

/**
 * Generate a `generateMetadata` override snippet that reads the Edge Config overlay and
 * applies head-only fixes for the current pathname. Drop into a page/layout server file.
 * @param {{key?:string}} [opts]  Edge Config item key apply/edge.mjs wrote (default "seoOverlay")
 * @returns {string} TS source snippet
 */
export function generateMetadataSnippet({ key = 'seoOverlay' } = {}) {
  return `// GENERATED by seo-bot (edge/middleware-codegen) — generateMetadata overlay reader.
// Reads the head-only overrides apply/edge.mjs PATCHed into Vercel Edge Config and merges
// them into this route's metadata. Resolves on the server → lands in the INITIAL HTML, so
// non-JS AI crawlers see the fix (defeats the OTTO pixel). Head fields ONLY (no body text).
import type { Metadata } from 'next';
import { get } from '@vercel/edge-config';

type Overlay = Record<string, {
  title?: string; description?: string; canonical?: string; robots?: string;
  og?: Record<string, unknown>; twitter?: Record<string, unknown>;
  hreflang?: Record<string, string>; jsonld?: unknown[]; capsule?: string;
}>;

export async function generateMetadata(
  { params }: { params: Promise<{ slug?: string[] }> },
): Promise<Metadata> {
  const { slug } = await params;
  const pathname = '/' + (slug?.join('/') ?? '');
  let rule: Overlay[string] | undefined;
  try { rule = (await get<Overlay>('${key}'))?.[pathname]; } catch { rule = undefined; }
  if (!rule) return {}; // no overlay → fall through to the page's own metadata

  const md: Metadata = {};
  if (rule.title) md.title = rule.title;
  if (rule.description) md.description = rule.description;
  if (rule.robots) md.robots = rule.robots;
  if (rule.canonical || rule.hreflang) {
    md.alternates = {};
    if (rule.canonical) md.alternates.canonical = rule.canonical;
    if (rule.hreflang) md.alternates.languages = rule.hreflang;
  }
  if (rule.og) md.openGraph = rule.og as Metadata['openGraph'];
  if (rule.twitter) md.twitter = rule.twitter as Metadata['twitter'];
  // JSON-LD is not part of the Metadata type — render it as a <script> in the page body
  // (server component) from the same overlay; the answer capsule mirrors into description
  // only if the page set none. Body VISIBLE text is never touched (no cloaking).
  return md;
}
`;
}

/**
 * Graduate ONE live edge rule into a source-PR payload for apply/nextjs.mjs.
 *
 * Per §2.3.3, every edge override is a hotfix that should become permanent repo source. Given
 * an edge rule {path, fields…}, emit the proposal payloads apply/nextjs.mjs already understands:
 *   • a fileWrite that drops a `seo-overlay.<slug>.ts` metadata module beside the route, OR
 *   • a review note when the change can't be safely located.
 * The caller passes these into apply/nextjs.mjs to open the graduation PR; once merged and
 * verifyParity confirms server-render, the edge override is removed.
 *
 * @param {{path:string, fields:object, routeFile?:string}} rule
 *   rule.path   pathname the overlay keys on (e.g. "/services/botox")
 *   rule.fields head-only overrides ({title, description, canonical, robots, jsonld, …})
 *   rule.routeFile optional repo path of the page (e.g. "app/services/[slug]/page.tsx")
 * @returns {{ type:'nextjs', proposals:Array }} payload for applyNextjs(cfg, payload, …)
 */
export function graduate(rule) {
  const path = rule?.path || '/';
  const slug = (path.replace(/^\/+|\/+$/g, '') || 'home').replace(/[^a-z0-9]+/gi, '-').toLowerCase();
  const fields = rule?.fields || {};
  const lines = [];
  if (fields.title) lines.push(`  title: ${JSON.stringify(fields.title)},`);
  if (fields.description) lines.push(`  description: ${JSON.stringify(fields.description)},`);
  if (fields.robots) lines.push(`  robots: ${JSON.stringify(fields.robots)},`);
  if (fields.canonical || fields.hreflang) {
    const alt = [];
    if (fields.canonical) alt.push(`    canonical: ${JSON.stringify(fields.canonical)},`);
    if (fields.hreflang) alt.push(`    languages: ${JSON.stringify(fields.hreflang)},`);
    lines.push(`  alternates: {\n${alt.join('\n')}\n  },`);
  }
  if (fields.og) lines.push(`  openGraph: ${JSON.stringify(fields.og)},`);
  if (fields.twitter) lines.push(`  twitter: ${JSON.stringify(fields.twitter)},`);

  const content = `// GENERATED by seo-bot graduate() — edge hotfix promoted to permanent source.
// Path: ${path}  ·  Import this from the route's server component:
//   import { metadata } from './seo-overlay.${slug}';
import type { Metadata } from 'next';

export const metadata: Metadata = {
${lines.join('\n')}
};
`;
  const overlayPath = `seo-bot/graduated/seo-overlay.${slug}.ts`;
  const proposals = [{
    id: `graduate:${slug}`,
    type: 'metadata.graduate',
    page: path,
    severity: 'medium',
    autoApplicable: true,
    rationale: `Graduate edge override for ${path} to server-rendered source (remove the edge rule once merged + parity-verified).`,
    fileWrite: { path: overlayPath, content },
  }];
  // JSON-LD graduates as a separate review note (must be wired into the page body by a human).
  if (Array.isArray(fields.jsonld) && fields.jsonld.length) {
    proposals.push({
      id: `graduate:${slug}:jsonld`,
      type: 'jsonld.graduate',
      page: path,
      severity: 'medium',
      autoApplicable: false,
      rationale: `Render ${fields.jsonld.length} JSON-LD node(s) for ${path} server-side (add a <script type="application/ld+json"> in the page server component).`,
      proposed: fields.jsonld,
    });
  }
  return { type: 'nextjs', proposals };
}

/** Convenience: graduate every rule in an apply/edge overlay object. */
export function graduateOverlay(overlay = {}) {
  const out = [];
  for (const [path, node] of Object.entries(overlay)) {
    const fields = {};
    for (const [k, v] of Object.entries(node)) { if (k !== '_meta') fields[fieldOf(k) === k ? k : k] = v; }
    out.push(graduate({ path, fields }));
  }
  return out;
}
