// seo-bot · render an audit result to a markdown report + persist it.

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { ROOT } from './config.mjs';
import { SEVERITY_RANK } from './util.mjs';

const ICON = { critical: '🔴', high: '🟠', medium: '🟡', low: '⚪', info: 'ℹ️' };

export function renderReport(r) {
  const L = [];
  L.push(`# SEO/AEO Audit — ${r.brand}`);
  L.push(`**${r.baseUrl}** · ${r.pageCount} pages sampled · ${new Date(r.ranAt).toUTCString()}`);
  L.push('');
  L.push(`## Health score: ${r.score}/100`);
  const s = r.bySeverity;
  L.push(`🔴 ${s.critical} critical · 🟠 ${s.high} high · 🟡 ${s.medium} medium · ⚪ ${s.low} low`);
  L.push('');

  // Work order — grouped by rule, highest severity/most frequent first
  L.push('## Prioritized work order');
  L.push('');
  L.push('| Sev | Issue | Pages | What to do |');
  L.push('|---|---|---|---|');
  const rules = [...r.byRule].sort((a, b) => (SEVERITY_RANK[a.severity] - SEVERITY_RANK[b.severity]) || (b.count - a.count));
  for (const ru of rules) {
    L.push(`| ${ICON[ru.severity] || ''} ${ru.severity} | \`${ru.rule}\` | ${ru.count} | ${ru.recommendation || ''} |`);
  }
  L.push('');

  // Site-level findings
  if (r.siteFindings.length) {
    L.push('## Site-level findings');
    for (const fn of r.siteFindings) L.push(`- ${ICON[fn.severity]} **${fn.rule}** — ${fn.message} → ${fn.recommendation}`);
    L.push('');
  }

  // Per-page (only pages with findings, condensed)
  L.push('## Per-page detail');
  L.push('');
  const withFindings = r.pages.filter((p) => p.findings.length).sort((a, b) => b.findings.length - a.findings.length);
  for (const p of withFindings) {
    const worst = p.findings.map((f) => SEVERITY_RANK[f.severity]).sort((a, b) => a - b)[0];
    const worstIcon = ICON[Object.keys(SEVERITY_RANK).find((k) => SEVERITY_RANK[k] === worst)] || '';
    L.push(`### ${worstIcon} ${p.url}`);
    if (p.parsed) L.push(`<sub>${p.parsed.bodyWords} words · ${p.parsed.jsonLdTypes.length ? 'schema: ' + [...new Set(p.parsed.jsonLdTypes)].join(', ') : 'no schema'} · ${p.parsed.internal} internal links</sub>`);
    for (const fn of p.findings.sort((a, b) => SEVERITY_RANK[a.severity] - SEVERITY_RANK[b.severity])) {
      L.push(`- ${ICON[fn.severity]} **${fn.rule}** — ${fn.message} _→ ${fn.recommendation}_`);
    }
    L.push('');
  }
  const clean = r.pages.length - withFindings.length;
  if (clean > 0) L.push(`_${clean} page(s) had no findings._`);
  L.push('');
  L.push('---');
  L.push('_Generated by seo-bot. Raw HTML only (what AI crawlers see). Not legal/medical advice._');
  return L.join('\n');
}

/** Persist the report + a machine-readable JSON next to it. Returns {mdPath, jsonPath}. */
export function saveReport(r) {
  const dir = join(ROOT, 'seo-bot', 'reports', r.client);
  mkdirSync(dir, { recursive: true });
  const stamp = r.ranAt.replace(/[:.]/g, '-');
  const mdPath = join(dir, `${stamp}.md`);
  const jsonPath = join(dir, `${stamp}.json`);
  const latest = join(dir, `latest.md`);
  const md = renderReport(r);
  writeFileSync(mdPath, md);
  writeFileSync(latest, md);
  // Strip cheerio-heavy parsed bodies from JSON to keep it small but useful.
  const slim = { ...r, pages: r.pages.map((p) => ({ url: p.url, status: p.status, findings: p.findings, parsed: p.parsed && { title: p.parsed.title, bodyWords: p.parsed.bodyWords, jsonLdTypes: [...new Set(p.parsed.jsonLdTypes)], internal: p.parsed.internal, modified: p.parsed.modified } })) };
  writeFileSync(jsonPath, JSON.stringify(slim, null, 2));
  return { mdPath, jsonPath, latest };
}
