// seo-bot · tactics/registry — the full white→grey→black ranking-lever registry,
// each labeled by hat, evidence tier, effect, penalty risk, durability, and how the
// bot may act on it. The owner accepts ranking-over-penalty-aversion on sites they
// OWN — so this registry exists to make that an INFORMED choice, not a blind one.
//
// ROUTING (automatable):
//   auto           = white-hat, low/no penalty, strong evidence → bot applies via rules/adapters
//   flag-opt-in    = effective but carries penalty risk → bot proposes; a human flips it ON per-tactic
//   manual         = off-site / human relationship work the bot can't do
//   do-not-automate= high-penalty or ILLEGAL → documented as knowledge; bot will NOT build the automation
//
// Seeded from the agency's own verified research (research/aeo-deep-research-2026.md
// §6 white-hat / §7 grey-black, evidence-tiered). The daily research loop proposes
// additions (credibility-gated); a human edits this file — it is never auto-written.

export const TACTICS = [
  // ---------------- WHITE HAT (strongest evidence, auto) ----------------
  { id: 'rank-top10', name: 'Rank organically in the top 10', hat: 'white', evidence: 'large-n (Ahrefs: 76%→ of AIO citations rank top-10)', tier: 'high', effect: 'dominant citation driver', penaltyRisk: 'none', durability: 'durable', automatable: 'auto', feature: 'the whole audit/loop', note: 'SEO is the prerequisite for AEO, not a competitor.' },
  { id: 'stats-quotes-citations', name: 'Add statistics, quotes, and cited sources to content', hat: 'white', evidence: 'controlled (Princeton GEO, KDD 2024, +40%)', tier: 'high', effect: '+visibility, biggest lift for underdog pages', penaltyRisk: 'none', durability: 'durable', automatable: 'flag-opt-in', feature: 'decide.mjs content proposals', note: 'Real, sourced stats only — fabricated authority is FTC-illegal.' },
  { id: 'server-rendered', name: 'Serve clean server-rendered HTML', hat: 'white', evidence: 'large-n (Vercel 500M+ fetches; AI crawlers don\'t run JS)', tier: 'high', effect: 'binary requirement for AEO', penaltyRisk: 'none', durability: 'durable', automatable: 'auto', feature: 'js-dependence rule + verify.mjs', note: 'Client-only content is invisible to ChatGPT/Claude/Perplexity.' },
  { id: 'allow-citation-bots', name: 'Don\'t block the AI citation bots', hat: 'white', evidence: 'large-n (~27% of B2B sites block at CDN)', tier: 'high', effect: 'eligibility for AI answers', penaltyRisk: 'none', durability: 'durable', automatable: 'auto', feature: 'ai-crawler-block rule', note: 'Allow GPTBot/OAI-SearchBot/ClaudeBot/PerplexityBot/Googlebot.' },
  { id: 'answer-first', name: 'Answer-first content (40-60w capsule, question headings, tables)', hat: 'white', evidence: 'large-n + practitioner (44% of ChatGPT citations from first third)', tier: 'high', effect: 'Layer-2 citation', penaltyRisk: 'none', durability: 'durable', automatable: 'auto', feature: 'answer-block / question-headings / answer-capsule-medspa rules', note: '' },
  { id: 'schema-entity', name: 'Valid schema + sameAs entity binding (MedicalBusiness, FAQ, Service)', hat: 'white', evidence: 'mixed/practitioner', tier: 'medium', effect: 'retrieval + entity resolution', penaltyRisk: 'none', durability: 'durable', automatable: 'auto', feature: 'med-spa schema rules', note: 'Ahrefs found no major JSON-LD uplift; still good hygiene + rich results.' },
  { id: 'freshness', name: 'Keep content genuinely fresh (re-date on real updates)', hat: 'white', evidence: 'large-n (<30d cited ~3.2x more)', tier: 'medium', effect: '+citation, strongest on Perplexity', penaltyRisk: 'low', durability: 'durable', automatable: 'auto', feature: 'freshness / medspa-freshness-ai rules', note: 'FAKE date-refresh is veto-listed (manipulation) — only real updates.' },
  { id: 'internal-link-variety', name: 'Internal-link mesh with varied descriptive anchors', hat: 'white', evidence: 'large-n (Zyppy 23M-link study: anchor variety > count)', tier: 'medium', effect: '+relevance/crawl', penaltyRisk: 'low', durability: 'durable', automatable: 'auto', feature: 'internal-links rule (+ planned anchor-variety rule)', note: '' },
  // From the 13-operator pioneer recon (Floate/Chou/Metehan dossiers, June 2026):
  { id: 'aeo-source-cluster-map', name: 'Prompt-variant source-cluster mapping (per-city citation whitelist)', hat: 'white', evidence: 'practitioner (Floate: "AI cites a predictable set of sources") + large-n (citation-source concentration)', tier: 'high', effect: 'turns "rank in AI" into a finite per-city target list (the recon foundation)', penaltyRisk: 'none', durability: 'durable', automatable: 'auto', feature: 'measure + serp (+ new source-cluster report)', note: 'Run N med-spa intent prompts/city across ChatGPT/Perplexity/AIO; log cited domains; cluster to the ~10-50 sources in 80%+ of answers → the placement+content backlog. Pure recon, the highest-value AEO play.' },
  { id: 'aeo-bing-first', name: 'Bing/Copilot-first indexing (submit sitemap + URLs to Bing)', hat: 'white', evidence: 'large-n (ChatGPT Search rides Bing\'s index ~87% overlap; Bing surface easier than AIO)', tier: 'medium', effect: 'faster citation on the ChatGPT/Copilot surface', penaltyRisk: 'none', durability: 'durable', automatable: 'auto', feature: 'data/bing.mjs + indexnow', note: 'Seed the easier Bing surface before fighting Google AIO (Floate: "Bing vs Google AI" split). SubmitUrlbatch + IndexNow already built.' },
  { id: 'aeo-video-transcript', name: 'Video + clean transcript optimisation for AI ingestion', hat: 'white', evidence: 'practitioner (LLMs ingest transcripts as citable text)', tier: 'low', effect: '+citable surface (YouTube is a top AI-cited domain)', penaltyRisk: 'none', durability: 'durable', automatable: 'flag-opt-in', feature: 'content', note: 'Per-city explainer videos + transcripts that mirror the answer capsules.' },

  // ---------------- GREY HAT (effective, penalty risk → opt-in) ----------------
  { id: 'own-comparison-pages', name: '"[Brand] vs / alternatives" comparison pages with REAL differentiation', hat: 'grey', evidence: 'practitioner (Scherck) + large-n (comparison pages +25.7% citations)', tier: 'medium', effect: '+BOFU citations', penaltyRisk: 'low', durability: 'medium', automatable: 'flag-opt-in', feature: 'decide content proposals', note: 'NEVER self-rank #1 (Lily Ray: cites you, recommends a rival ~69%).' },
  { id: 'programmatic-seo', name: 'Programmatic / pSEO pages at scale (with unique real data)', hat: 'grey', evidence: 'large-n (works with data; backfires thin)', tier: 'medium', effect: 'broad long-tail capture', penaltyRisk: 'medium', durability: 'medium', automatable: 'flag-opt-in', feature: 'template + data pipeline', note: 'Thin/duplicative pSEO → scaled-content-abuse penalty (50-80% drops). Needs real per-page data.' },
  { id: 'third-party-listicles', name: 'Earn (or pay for) inclusion in third-party "best of" listicles', hat: 'grey', evidence: 'large-n (63% of AI citations are listicles)', tier: 'high', effect: '+AI citation odds ~6.5x via third-party', penaltyRisk: 'low', durability: 'medium', automatable: 'manual', feature: 'citations/off-site', note: 'Paid placement is a real market; FTC disclosure gray area.' },
  { id: 'reddit-ugc-seeding', name: 'Reddit / community presence ("is X legit", genuine participation)', hat: 'grey', evidence: 'large-n (UGC ≈ half of agent citations; Perplexity→Reddit)', tier: 'high', effect: '+citation in UGC-heavy engines', penaltyRisk: 'medium', durability: 'low', automatable: 'manual', feature: 'off-site', note: 'Aged-account/upvote market exists but is bannable + volatile (Reddit re-tunes source weight fast).' },
  { id: 'review-velocity', name: 'Drive real review volume + recency (compliantly)', hat: 'grey', evidence: 'large-n (Seer: 1% vs 53.5% citation at 1-13 reviews)', tier: 'high', effect: 'major citation threshold', penaltyRisk: 'low', durability: 'durable', automatable: 'manual', feature: 'citations/GBP', note: 'GATING / incentivized / in-lobby solicitation is ILLEGAL (FTC) + suspension-risk — never automate (see do-not-automate).' },
  { id: 'aeo-city-listicle', name: '"Best [service] in [city]" listicle AS the cited source (real editorial, never self-#1)', hat: 'grey', evidence: 'large-n (63% of AI citations are listicles) + practitioner (Chou: "2026 = year of the listicle")', tier: 'high', effect: 'become the structured comparison source LLMs quote for local intent', penaltyRisk: 'medium', durability: 'medium', automatable: 'flag-opt-in', feature: 'content + ItemList schema + locations', note: 'A med-spa DIRECTORY is this listicle at scale: genuine ranking criteria + real reviews + ItemList schema + frequent re-touch + submit to Bing. NEVER self-rank #1 — Chou\'s self-#1 listicle network was demoted Jan-2026 (−49%); Lily Ray: AI recommends a rival ~69% anyway.' },
  { id: 'aeo-entity-cooccurrence', name: 'Entity co-occurrence building (unlinked brand mentions)', hat: 'grey', evidence: 'practitioner (Floate: 30-60 trusted sources) + mixed (unlinked mentions as entity signal)', tier: 'medium', effect: 'LLMs associate the brand with the topic/city via repeated co-mention', penaltyRisk: 'low', durability: 'durable', automatable: 'manual', feature: 'off-site / entity', note: 'Consistent "<Directory> + <treatment> + <city>" co-mentions across local press, niche blogs, Wikidata, schema. White when earned; grey if paid-stealth or fabricated.' },

  // ---------------- BLACK HAT (documented as knowledge; not auto-built) ----------------
  { id: 'mass-ai-content', name: 'Mass AI-generated content at scale', hat: 'black', evidence: 'large-n (Google scaled-content-abuse + S-BERT/S-CTS detection)', tier: 'high', effect: 'short-term volume, then 50-80% traffic drops', penaltyRisk: 'high', durability: 'collapsing', automatable: 'do-not-automate', feature: '—', note: 'Detectable (embedding footprint + burstiness) and demoted. The bot optimizes structure, not volume.' },
  { id: 'preference-manipulation', name: 'Strategic text sequences / LLM preference manipulation', hat: 'black', evidence: 'peer-reviewed (2.5x-7.2x on weak models; ~0% on Claude Sonnet 4.6)', tier: 'medium', effect: 'model-dependent; near-zero on frontier', penaltyRisk: 'medium', durability: 'low', automatable: 'do-not-automate', feature: '—', note: 'Works on fast/cheap models; flagged + neutralized by frontier models.' },
  { id: 'fabricated-consensus', name: 'Fabricated/synthetic consensus across fake sources', hat: 'black', evidence: 'peer-reviewed (39%→77% on Gemini Flash; ~0% Claude)', tier: 'medium', effect: 'model-dependent', penaltyRisk: 'high', durability: 'low', automatable: 'do-not-automate', feature: '—', note: 'High legal/platform risk; structurally self-defeating at scale (prisoner\'s dilemma).' },
  { id: 'ctr-manipulation', name: 'CTR manipulation (Jacky Chou\'s BrowserBlast / click farms)', hat: 'black', evidence: 'large-n (NavBoost real per DOJ + 2024 leak) but manipulation = case-study/anecdote', tier: 'low', effect: '48-72h spike that FADES; durable-NEGATIVE', penaltyRisk: 'high', durability: 'low', automatable: 'do-not-automate', legalBlock: false, feature: '—', note: 'CTR-as-signal is real (NavBoost) but Google aggregates ~13mo + discards bot/inconsistent clicks → "you get clapped". This is the flagship thing Jacky Chou sells.' },
  { id: 'parasite-seo', name: 'Parasite SEO / site-reputation abuse (lease authority subdomains)', hat: 'black', evidence: 'practitioner', tier: 'medium', effect: 'worked, now demoted', penaltyRisk: 'high', durability: 'dying', automatable: 'do-not-automate', feature: '—', note: 'Google Site Reputation Abuse policy deindexes/demotes; EU DMA probe.' },
  { id: 'pbn-expired-domains', name: 'PBNs / expired-domain redirects', hat: 'black', evidence: 'practitioner', tier: 'low', effect: 'weak ROI', penaltyRisk: 'high', durability: 'dying', automatable: 'do-not-automate', feature: '—', note: 'Strong detection + penalties; only marginal as "mention networks".' },
  { id: 'aeo-prompt-injection', name: 'Hidden text / indirect prompt injection into LLM-ingested pages', hat: 'black', evidence: 'demonstrated (Palo Alto / Trend Micro invisible-injection research)', tier: 'medium', effect: 'biases models until detected; burns trust with the target engines', penaltyRisk: 'high', durability: 'low', automatable: 'do-not-automate', feature: '— (parity / cloaking-guard detects it)', note: 'Off-screen CSS / opacity:0 / SVG-CDATA / invisible-Unicode instructions telling the AI what to say. Against Google/OpenAI policy; deceptive. Floate sells it ("Black Hat AI Techniques"). Record-for-defense only — flag it on competitors, never emit it.' },
  { id: 'aeo-buy-listicle-pbn', name: 'Buy self-#1 listicle / PBN placements for LLM mentions', hat: 'black', evidence: 'practitioner (Chou sells $99 100-PBN packs) + large-n (Google Jan-2026 update hit self-#1 listicle networks, up to −49%)', tier: 'low', effect: 'short-lived; already penalized', penaltyRisk: 'high', durability: 'dying', automatable: 'do-not-automate', feature: '—', note: 'PBN/reciprocal-listing networks that insert you at #1. The legit cousin is aeo-city-listicle / third-party-listicles (EARNED). Threat model: competitors may spam these at you.' },
  { id: 'reddit-account-farming', name: 'Reddit account-farming + bought upvotes/comments to seed LLM answers', hat: 'black', evidence: 'practitioner (Chou SOP: ~100 aged accounts, residential proxies, $0.05 upvotes, paid narrative steering)', tier: 'low', effect: 'volatile + bannable; Reddit re-tunes source weight fast', penaltyRisk: 'illegal', durability: 'low', automatable: 'do-not-automate', legalBlock: true, vetoMapsTo: ['fake reviews'], feature: '—', note: 'Coordinated inauthentic behavior + fake endorsements (Reddit TOS + FTC). The legit cousin is reddit-ugc-seeding (real, disclosed human answers). Hard refusal — bot may DRAFT a real disclosed answer, never farm accounts or buy upvotes.' },
  { id: 'cloaking', name: 'Agent-aware cloaking (serve crawlers different content)', hat: 'black', evidence: 'demonstrated (SPLX vs Atlas, Oct 2025)', tier: 'medium', effect: 'works until parity-checked', penaltyRisk: 'high', durability: 'low', automatable: 'do-not-automate', feature: '—', note: 'Deceptive; high penalty once detected.' },
  { id: 'fake-reviews', name: 'Fake / incentivized / gated reviews', hat: 'black', evidence: 'n/a', tier: 'n/a', effect: 'n/a', penaltyRisk: 'illegal', durability: 'n/a', automatable: 'do-not-automate', legalBlock: true, vetoMapsTo: ['fake reviews', 'review gating'], feature: 'review-authenticity rule (flag-only)', note: 'FTC 16 CFR 465 — final Oct 2024, ~$53k/violation, first warning letters Dec 2025; $4.2M gating fine. The bot detects + flags; it will NEVER generate or solicit. Hard legal refusal regardless of measured lift.' },
];

const RANK = { auto: 0, 'flag-opt-in': 1, manual: 2, 'do-not-automate': 3 };

/** Grouped, risk-labeled view for the CLI. */
export function tacticsView() {
  const hats = { white: [], grey: [], black: [] };
  for (const t of TACTICS) (hats[t.hat] || (hats[t.hat] = [])).push(t);
  return hats;
}

/** Which tactics the bot may act on now for a client, by opt-in policy.
 *  Defense in depth: anything legalBlock or veto-mapped is dropped even if mis-opted-in. */
export function actionable(cfg = {}) {
  const optedIn = new Set(cfg.tacticsOptIn || []); // per-client explicit opt-in for grey levers
  return TACTICS
    .filter((t) => !t.legalBlock && !(t.vetoMapsTo && t.vetoMapsTo.length))
    .filter((t) => t.automatable === 'auto' || (t.automatable === 'flag-opt-in' && optedIn.has(t.id)))
    .sort((a, b) => RANK[a.automatable] - RANK[b.automatable]);
}
